name: pyrhessys
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - xarray>=0.15.0
  - pandas
  - netcdf4>=1.2.5
  - numpy>=1.11.2
  - numba
  - scipy
  - dask-jobqueue
  - dask
  - distributed
  - toolz
  - pytest
  - fiona
  - cartopy
  - shapely
  - seaborn
  - matplotlib
  - geopandas
  - jupyter
  - imageio
  - pip
  - geoviews=1.6.6
  - geoviews-core=1.6.6
  - holoviews=1.14.1   
  - pip:
    - hs_restclient
    - hydroeval
    - sklearn
    - pyDOE
    - ipyplot
    - bs4
    - cdo-api-py
    - wget